server:
  port: 8080
  logging:
    file: true
    level: debug
    path: "log/lzblogs"
  rbacModelConf: "./model.conf"
  jwtSecret: "lzblogsjwtsecret"

database:
  host: "127.0.0.1"
  port: 33060
  name: "lzblogs"
  user: "luozi"
  password: "123456"
  migrate: true

oauth:
  github:
    clientID: "8dff55d10fdfd78b3432"
    clientSecret: "a9e8f8caca901f4194a977c9426d52cc6802ded3"